name: Build app and upload to release

on:
  release:
    types: [ published ]

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          #          - platform: 'macos-latest' # for Arm based macs (M1 and above).
          #            args: '--target aarch64-apple-darwin'
          #          - platform: 'macos-latest' # for Intel based macs.
          #            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'ubuntu-22.04-arm'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' || matrix.platform == 'ubuntu-22.04-arm' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - name: Install frontend dependencies
        run: yarn install

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          # Pointing to the tauri directory for caching
          workspaces: "src-tauri -> target"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ github.event.release.id }}
          args: ${{ matrix.args }}

  build-and-publish-flatpak:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            arch: x86_64
          - platform: 'ubuntu-22.04-arm'
            arch: aarch64

    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    needs: [ build-tauri ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install frontend dependencies
        run: yarn install


      - name: Generate flatpak manifest
        run: node ./src-tauri/bundle/render-templates.js remote ${{ github.event.release.tag_name }}

      - name: 'Upload flatpak manifest'
        if: matrix.platform == 'ubuntu-22.04'
        run: |

          gh release upload ${{ github.event.release.tag_name }} "./src-tauri/bundle/generated/io.github.neisvestney.qw-cat.yml#Flatpak manifest (yml)"
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: qw-cat-${{ matrix.arch }}-${{ github.event.release.tag_name }}.flatpak
          manifest-path: ./src-tauri/bundle/generated/io.github.neisvestney.qw-cat.yml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
          verbose: true

      - name: 'Upload flatpak artifact'
        run: |
          gh release upload ${{ github.event.release.tag_name }} qw-cat-${{ matrix.arch }}-${{ github.event.release.tag_name }}.flatpak
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [ build-tauri, build-and-publish-flatpak ]

    steps:
      - name: Publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ github.event.release.id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
