name: Checks

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src-tauri/**'
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/lints.yml'
      - 'tsconfig.json'
      - 'sconfig.node.json'
      - 'ite.config.ts'
      - 'index.html'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src-tauri/**'
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/lints.yml'
      - 'tsconfig.json'
      - 'sconfig.node.json'
      - 'ite.config.ts'
      - 'index.html'

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Rust (Format & Clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          version: 1.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          # Pointing to the tauri directory for caching
          workspaces: "src-tauri -> target"

      - name: Check formatting
        run: cargo fmt --all -- --check
        working-directory: src-tauri

      - name: Run clippy
        run: cargo clippy -- -D warnings
        working-directory: src-tauri
