name: Checks

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src-tauri/**'
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/lints.yml'
      - 'tsconfig.json'
      - `tsconfig.node.json`
      - `vite.config.ts`
      - `index.html`
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src-tauri/**'
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/lints.yml'
      - 'tsconfig.json'
      - `tsconfig.node.json`
      - `vite.config.ts`
      - `index.html`

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Rust (Format & Clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          # Pointing to the tauri directory for caching
          workspaces: "src-tauri -> target"

      - name: Check formatting
        run: cargo fmt --all -- --check
        working-directory: src-tauri

      - name: Run clippy
        run: cargo clippy -- -D warnings
        working-directory: src-tauri
